// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5-xrlNygWNRTu2hpbzJ7rQVGIwl6PFjA',
    appId: '1:838400405205:web:10864c0eb45da83f8f7c5c',
    messagingSenderId: '838400405205',
    projectId: 'readzone-e39ac',
    authDomain: 'readzone-e39ac.firebaseapp.com',
    storageBucket: 'readzone-e39ac.appspot.com',
    measurementId: 'G-GEW9Y86W38',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2YZvsAqy7thqKL3_FH9G2x8_9EJDXNCE',
    appId: '1:838400405205:android:e391e9b9570cbf068f7c5c',
    messagingSenderId: '838400405205',
    projectId: 'readzone-e39ac',
    storageBucket: 'readzone-e39ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKhU_M5egNmMGsEkbK6HbQGSnKZMLUZvc',
    appId: '1:838400405205:ios:5302f2bea37e4c028f7c5c',
    messagingSenderId: '838400405205',
    projectId: 'readzone-e39ac',
    storageBucket: 'readzone-e39ac.appspot.com',
    iosBundleId: 'com.example.readZone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKhU_M5egNmMGsEkbK6HbQGSnKZMLUZvc',
    appId: '1:838400405205:ios:5302f2bea37e4c028f7c5c',
    messagingSenderId: '838400405205',
    projectId: 'readzone-e39ac',
    storageBucket: 'readzone-e39ac.appspot.com',
    iosBundleId: 'com.example.readZone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5-xrlNygWNRTu2hpbzJ7rQVGIwl6PFjA',
    appId: '1:838400405205:web:d6597157974007258f7c5c',
    messagingSenderId: '838400405205',
    projectId: 'readzone-e39ac',
    authDomain: 'readzone-e39ac.firebaseapp.com',
    storageBucket: 'readzone-e39ac.appspot.com',
    measurementId: 'G-L3CQB96SM0',
  );
}
